In [1]:
import numpy as np


In [2]:
a=np.arange(10,19).reshape(3,3)

In [3]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
a[::1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
a[::2]

array([[10, 11, 12],
       [16, 17, 18]])

In [6]:
a[::3]

array([[10, 11, 12]])

In [7]:
a[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [8]:
a[(0,2),0:2]

array([[10, 11],
       [16, 17]])

In [9]:
b=np.arange(99)

In [10]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [11]:
b[22:88]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87])

In [12]:
b[22:88:92]

array([22])

In [13]:
b[22:88:1]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87])

In [14]:
b[22:88:2]

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86])

In [15]:
b[22:88:3]

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70,
       73, 76, 79, 82, 85])

In [16]:
b[22:88:10]

array([22, 32, 42, 52, 62, 72, 82])

In [17]:
b[22:88:-1]

array([], dtype=int32)

In [18]:
b[88:22:-1]

array([88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72,
       71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55,
       54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38,
       37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23])

In [19]:
b[88:22:-2]

array([88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56,
       54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24])

In [20]:
b[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
b[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [22]:
b[:5:]

array([0, 1, 2, 3, 4])

In [23]:
a[0:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
a[0,:] #same output can be obtained by using a[0]

array([10, 11, 12])

In [25]:
a[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [26]:
a.flat

In [27]:
print(a)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [33]:
np.apply_along_axis(np.mean,axis=0,arr=a)

array([13., 14., 15.])

In [35]:
np.apply_along_axis(np.mean,axis=1,arr=a)

array([11., 14., 17.])

In [36]:
def halfOfvalue(x):
    return x/2

In [37]:
np.apply_along_axis(halfOfvalue,axis=0,arr=a)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [39]:
def sub_matrix(x):
    return x-1

In [40]:
np.apply_along_axis(sub_matrix,axis=0,arr=a)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [41]:
a=np.random.random((4,4))

In [42]:
a

array([[0.56190087, 0.89399214, 0.85856911, 0.68789245],
       [0.92752179, 0.77144822, 0.6383895 , 0.68217329],
       [0.79478909, 0.0833989 , 0.64382426, 0.34593324],
       [0.85759326, 0.66330383, 0.15768913, 0.36247904]])

In [43]:
c=a>0.6

In [44]:
c

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True, False, False]])

In [47]:
b=a[a>0.5]

In [48]:
b

array([0.56190087, 0.89399214, 0.85856911, 0.68789245, 0.92752179,
       0.77144822, 0.6383895 , 0.68217329, 0.79478909, 0.64382426,
       0.85759326, 0.66330383])

In [49]:
d=a[a*0.5]

IndexError: arrays used as indices must be of integer (or boolean) type

In [50]:
a

array([[0.56190087, 0.89399214, 0.85856911, 0.68789245],
       [0.92752179, 0.77144822, 0.6383895 , 0.68217329],
       [0.79478909, 0.0833989 , 0.64382426, 0.34593324],
       [0.85759326, 0.66330383, 0.15768913, 0.36247904]])

In [52]:
a=np.random.random(12)
a

array([0.64755626, 0.53414977, 0.07038328, 0.46137565, 0.75334382,
       0.1858444 , 0.59865624, 0.38753215, 0.67855897, 0.22200117,
       0.45061276, 0.30979589])

In [55]:
a=a.reshape(2,6)
a

array([[0.64755626, 0.53414977, 0.07038328, 0.46137565, 0.75334382,
        0.1858444 ],
       [0.59865624, 0.38753215, 0.67855897, 0.22200117, 0.45061276,
        0.30979589]])

In [58]:
a.shape=(3,4)
a

array([[0.64755626, 0.53414977, 0.07038328, 0.46137565],
       [0.75334382, 0.1858444 , 0.59865624, 0.38753215],
       [0.67855897, 0.22200117, 0.45061276, 0.30979589]])

In [59]:
a.ravel()

array([0.64755626, 0.53414977, 0.07038328, 0.46137565, 0.75334382,
       0.1858444 , 0.59865624, 0.38753215, 0.67855897, 0.22200117,
       0.45061276, 0.30979589])

In [60]:
b=a

In [61]:
b

array([[0.64755626, 0.53414977, 0.07038328, 0.46137565],
       [0.75334382, 0.1858444 , 0.59865624, 0.38753215],
       [0.67855897, 0.22200117, 0.45061276, 0.30979589]])

In [62]:
a

array([[0.64755626, 0.53414977, 0.07038328, 0.46137565],
       [0.75334382, 0.1858444 , 0.59865624, 0.38753215],
       [0.67855897, 0.22200117, 0.45061276, 0.30979589]])

In [63]:
a.shape=(2,6)
a

array([[0.64755626, 0.53414977, 0.07038328, 0.46137565, 0.75334382,
        0.1858444 ],
       [0.59865624, 0.38753215, 0.67855897, 0.22200117, 0.45061276,
        0.30979589]])

In [64]:
a.transpose()

array([[0.64755626, 0.59865624],
       [0.53414977, 0.38753215],
       [0.07038328, 0.67855897],
       [0.46137565, 0.22200117],
       [0.75334382, 0.45061276],
       [0.1858444 , 0.30979589]])

In [70]:
g=np.arange(16).reshape(4,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
[b,c] = np.hspilt(g,2)

AttributeError: module 'numpy' has no attribute 'hspilt'

In [72]:
a=np.arange(16).reshape(4,4)

In [73]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
c=a.copy()

In [75]:
c.shape=(2,8)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [87]:
a=np.array([(1,'first',0.2,1+2j),(2,'second',0.4,1-2j),(3,'third',0.3,3+2j)],dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [88]:
a

array([(1, b'first', 0.2, 1.+2.j), (2, b'second', 0.4, 1.-2.j),
       (3, b'third', 0.3, 3.+2.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [89]:
a[0]

(1, b'first', 0.2, 1.+2.j)

In [90]:
a[1]

(2, b'second', 0.4, 1.-2.j)

In [91]:
a[2]

(3, b'third', 0.3, 3.+2.j)

In [94]:
a['id']

array([1, 2, 3], dtype=int16)

In [95]:
a['position']

array([b'first', b'second', b'third'], dtype='|S6')

In [96]:
a['value']

array([0.2, 0.4, 0.3], dtype=float32)

In [97]:
a['complex']

array([1.+2.j, 1.-2.j, 3.+2.j], dtype=complex64)

In [98]:
a.dtype.names=('idx','order','values','cplx')

In [99]:
a

array([(1, b'first', 0.2, 1.+2.j), (2, b'second', 0.4, 1.-2.j),
       (3, b'third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('values', '<f4'), ('cplx', '<c8')])

In [100]:
np.save('saved_data',a)

In [102]:
data=np.load('saved_data.npy')

In [103]:
data

array([(1, b'first', 0.2, 1.+2.j), (2, b'second', 0.4, 1.-2.j),
       (3, b'third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('values', '<f4'), ('cplx', '<c8')])

In [104]:
data=np.load('saved_data.npy')
data

array([(1, b'first', 0.2, 1.+2.j), (2, b'second', 0.4, 1.-2.j),
       (3, b'third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('values', '<f4'), ('cplx', '<c8')])

In [105]:
data=np.genfromtxt('01_data.csv',delimiter=',',names=True)

ValueError: Some errors were detected !
    Line #2 (got 13 columns instead of 12)
    Line #3 (got 13 columns instead of 12)
    Line #4 (got 13 columns instead of 12)
    Line #5 (got 13 columns instead of 12)
    Line #6 (got 13 columns instead of 12)
    Line #7 (got 13 columns instead of 12)
    Line #8 (got 13 columns instead of 12)
    Line #9 (got 13 columns instead of 12)
    Line #10 (got 13 columns instead of 12)
    Line #11 (got 13 columns instead of 12)
    Line #12 (got 13 columns instead of 12)
    Line #13 (got 13 columns instead of 12)
    Line #14 (got 13 columns instead of 12)
    Line #15 (got 13 columns instead of 12)
    Line #16 (got 13 columns instead of 12)
    Line #17 (got 13 columns instead of 12)
    Line #18 (got 13 columns instead of 12)
    Line #19 (got 13 columns instead of 12)
    Line #20 (got 13 columns instead of 12)
    Line #21 (got 13 columns instead of 12)
    Line #22 (got 13 columns instead of 12)
    Line #23 (got 13 columns instead of 12)
    Line #24 (got 13 columns instead of 12)
    Line #25 (got 13 columns instead of 12)
    Line #26 (got 13 columns instead of 12)
    Line #27 (got 13 columns instead of 12)
    Line #28 (got 13 columns instead of 12)
    Line #29 (got 13 columns instead of 12)
    Line #30 (got 13 columns instead of 12)
    Line #31 (got 13 columns instead of 12)
    Line #32 (got 13 columns instead of 12)
    Line #33 (got 13 columns instead of 12)
    Line #34 (got 13 columns instead of 12)
    Line #35 (got 13 columns instead of 12)
    Line #36 (got 13 columns instead of 12)
    Line #37 (got 13 columns instead of 12)
    Line #38 (got 13 columns instead of 12)
    Line #39 (got 13 columns instead of 12)
    Line #40 (got 13 columns instead of 12)
    Line #41 (got 13 columns instead of 12)
    Line #42 (got 13 columns instead of 12)
    Line #43 (got 13 columns instead of 12)
    Line #44 (got 13 columns instead of 12)
    Line #45 (got 13 columns instead of 12)
    Line #46 (got 13 columns instead of 12)
    Line #47 (got 13 columns instead of 12)
    Line #48 (got 13 columns instead of 12)
    Line #49 (got 13 columns instead of 12)
    Line #50 (got 13 columns instead of 12)
    Line #51 (got 13 columns instead of 12)
    Line #52 (got 13 columns instead of 12)
    Line #53 (got 13 columns instead of 12)
    Line #54 (got 13 columns instead of 12)
    Line #55 (got 13 columns instead of 12)
    Line #56 (got 13 columns instead of 12)
    Line #57 (got 13 columns instead of 12)
    Line #58 (got 13 columns instead of 12)
    Line #59 (got 13 columns instead of 12)
    Line #60 (got 13 columns instead of 12)
    Line #61 (got 13 columns instead of 12)
    Line #62 (got 13 columns instead of 12)
    Line #63 (got 13 columns instead of 12)
    Line #64 (got 13 columns instead of 12)
    Line #65 (got 13 columns instead of 12)
    Line #66 (got 13 columns instead of 12)
    Line #67 (got 13 columns instead of 12)
    Line #68 (got 13 columns instead of 12)
    Line #69 (got 13 columns instead of 12)
    Line #70 (got 13 columns instead of 12)
    Line #71 (got 13 columns instead of 12)
    Line #72 (got 13 columns instead of 12)
    Line #73 (got 13 columns instead of 12)
    Line #74 (got 13 columns instead of 12)
    Line #75 (got 13 columns instead of 12)
    Line #76 (got 13 columns instead of 12)
    Line #77 (got 13 columns instead of 12)
    Line #78 (got 13 columns instead of 12)
    Line #79 (got 13 columns instead of 12)
    Line #80 (got 13 columns instead of 12)
    Line #81 (got 13 columns instead of 12)
    Line #82 (got 13 columns instead of 12)
    Line #83 (got 13 columns instead of 12)
    Line #84 (got 13 columns instead of 12)
    Line #85 (got 13 columns instead of 12)
    Line #86 (got 13 columns instead of 12)
    Line #87 (got 13 columns instead of 12)
    Line #88 (got 13 columns instead of 12)
    Line #89 (got 13 columns instead of 12)
    Line #90 (got 13 columns instead of 12)
    Line #91 (got 13 columns instead of 12)
    Line #92 (got 13 columns instead of 12)
    Line #93 (got 13 columns instead of 12)
    Line #94 (got 13 columns instead of 12)
    Line #95 (got 13 columns instead of 12)
    Line #96 (got 13 columns instead of 12)
    Line #97 (got 13 columns instead of 12)
    Line #98 (got 13 columns instead of 12)
    Line #99 (got 13 columns instead of 12)
    Line #100 (got 13 columns instead of 12)
    Line #101 (got 13 columns instead of 12)
    Line #102 (got 13 columns instead of 12)
    Line #103 (got 13 columns instead of 12)
    Line #104 (got 13 columns instead of 12)
    Line #105 (got 13 columns instead of 12)
    Line #106 (got 13 columns instead of 12)
    Line #107 (got 13 columns instead of 12)
    Line #108 (got 13 columns instead of 12)
    Line #109 (got 13 columns instead of 12)
    Line #110 (got 13 columns instead of 12)
    Line #111 (got 13 columns instead of 12)
    Line #112 (got 13 columns instead of 12)
    Line #113 (got 13 columns instead of 12)
    Line #114 (got 13 columns instead of 12)
    Line #115 (got 13 columns instead of 12)
    Line #116 (got 13 columns instead of 12)
    Line #117 (got 13 columns instead of 12)
    Line #118 (got 13 columns instead of 12)
    Line #119 (got 13 columns instead of 12)
    Line #120 (got 13 columns instead of 12)
    Line #121 (got 13 columns instead of 12)
    Line #122 (got 13 columns instead of 12)
    Line #123 (got 13 columns instead of 12)
    Line #124 (got 13 columns instead of 12)
    Line #125 (got 13 columns instead of 12)
    Line #126 (got 13 columns instead of 12)
    Line #127 (got 13 columns instead of 12)
    Line #128 (got 13 columns instead of 12)
    Line #129 (got 13 columns instead of 12)
    Line #130 (got 13 columns instead of 12)
    Line #131 (got 13 columns instead of 12)
    Line #132 (got 13 columns instead of 12)
    Line #133 (got 13 columns instead of 12)
    Line #134 (got 13 columns instead of 12)
    Line #135 (got 13 columns instead of 12)
    Line #136 (got 13 columns instead of 12)
    Line #137 (got 13 columns instead of 12)
    Line #138 (got 13 columns instead of 12)
    Line #139 (got 13 columns instead of 12)
    Line #140 (got 13 columns instead of 12)
    Line #141 (got 13 columns instead of 12)
    Line #142 (got 13 columns instead of 12)
    Line #143 (got 13 columns instead of 12)
    Line #144 (got 13 columns instead of 12)
    Line #145 (got 13 columns instead of 12)
    Line #146 (got 13 columns instead of 12)
    Line #147 (got 13 columns instead of 12)
    Line #148 (got 13 columns instead of 12)
    Line #149 (got 13 columns instead of 12)
    Line #150 (got 13 columns instead of 12)
    Line #151 (got 13 columns instead of 12)
    Line #152 (got 13 columns instead of 12)
    Line #153 (got 13 columns instead of 12)
    Line #154 (got 13 columns instead of 12)
    Line #155 (got 13 columns instead of 12)
    Line #156 (got 13 columns instead of 12)
    Line #157 (got 13 columns instead of 12)
    Line #158 (got 13 columns instead of 12)
    Line #159 (got 13 columns instead of 12)
    Line #160 (got 13 columns instead of 12)
    Line #161 (got 13 columns instead of 12)
    Line #162 (got 13 columns instead of 12)
    Line #163 (got 13 columns instead of 12)
    Line #164 (got 13 columns instead of 12)
    Line #165 (got 13 columns instead of 12)
    Line #166 (got 13 columns instead of 12)
    Line #167 (got 13 columns instead of 12)
    Line #168 (got 13 columns instead of 12)
    Line #169 (got 13 columns instead of 12)
    Line #170 (got 13 columns instead of 12)
    Line #171 (got 13 columns instead of 12)
    Line #172 (got 13 columns instead of 12)
    Line #173 (got 13 columns instead of 12)
    Line #174 (got 13 columns instead of 12)
    Line #175 (got 13 columns instead of 12)
    Line #176 (got 13 columns instead of 12)
    Line #177 (got 13 columns instead of 12)
    Line #178 (got 13 columns instead of 12)
    Line #179 (got 13 columns instead of 12)
    Line #180 (got 13 columns instead of 12)
    Line #181 (got 13 columns instead of 12)
    Line #182 (got 13 columns instead of 12)
    Line #183 (got 13 columns instead of 12)
    Line #184 (got 13 columns instead of 12)
    Line #185 (got 13 columns instead of 12)
    Line #186 (got 13 columns instead of 12)
    Line #187 (got 13 columns instead of 12)
    Line #188 (got 13 columns instead of 12)
    Line #189 (got 13 columns instead of 12)
    Line #190 (got 13 columns instead of 12)
    Line #191 (got 13 columns instead of 12)
    Line #192 (got 13 columns instead of 12)
    Line #193 (got 13 columns instead of 12)
    Line #194 (got 13 columns instead of 12)
    Line #195 (got 13 columns instead of 12)
    Line #196 (got 13 columns instead of 12)
    Line #197 (got 13 columns instead of 12)
    Line #198 (got 13 columns instead of 12)
    Line #199 (got 13 columns instead of 12)
    Line #200 (got 13 columns instead of 12)
    Line #201 (got 13 columns instead of 12)
    Line #202 (got 13 columns instead of 12)
    Line #203 (got 13 columns instead of 12)
    Line #204 (got 13 columns instead of 12)
    Line #205 (got 13 columns instead of 12)
    Line #206 (got 13 columns instead of 12)
    Line #207 (got 13 columns instead of 12)
    Line #208 (got 13 columns instead of 12)
    Line #209 (got 13 columns instead of 12)
    Line #210 (got 13 columns instead of 12)
    Line #211 (got 13 columns instead of 12)
    Line #212 (got 13 columns instead of 12)
    Line #213 (got 13 columns instead of 12)
    Line #214 (got 13 columns instead of 12)
    Line #215 (got 13 columns instead of 12)
    Line #216 (got 13 columns instead of 12)
    Line #217 (got 13 columns instead of 12)
    Line #218 (got 13 columns instead of 12)
    Line #219 (got 13 columns instead of 12)
    Line #220 (got 13 columns instead of 12)
    Line #221 (got 13 columns instead of 12)
    Line #222 (got 13 columns instead of 12)
    Line #223 (got 13 columns instead of 12)
    Line #224 (got 13 columns instead of 12)
    Line #225 (got 13 columns instead of 12)
    Line #226 (got 13 columns instead of 12)
    Line #227 (got 13 columns instead of 12)
    Line #228 (got 13 columns instead of 12)
    Line #229 (got 13 columns instead of 12)
    Line #230 (got 13 columns instead of 12)
    Line #231 (got 13 columns instead of 12)
    Line #232 (got 13 columns instead of 12)
    Line #233 (got 13 columns instead of 12)
    Line #234 (got 13 columns instead of 12)
    Line #235 (got 13 columns instead of 12)
    Line #236 (got 13 columns instead of 12)
    Line #237 (got 13 columns instead of 12)
    Line #238 (got 13 columns instead of 12)
    Line #239 (got 13 columns instead of 12)
    Line #240 (got 13 columns instead of 12)
    Line #241 (got 13 columns instead of 12)
    Line #242 (got 13 columns instead of 12)
    Line #243 (got 13 columns instead of 12)
    Line #244 (got 13 columns instead of 12)
    Line #245 (got 13 columns instead of 12)
    Line #246 (got 13 columns instead of 12)
    Line #247 (got 13 columns instead of 12)
    Line #248 (got 13 columns instead of 12)
    Line #249 (got 13 columns instead of 12)
    Line #250 (got 13 columns instead of 12)
    Line #251 (got 13 columns instead of 12)
    Line #252 (got 13 columns instead of 12)
    Line #253 (got 13 columns instead of 12)
    Line #254 (got 13 columns instead of 12)
    Line #255 (got 13 columns instead of 12)
    Line #256 (got 13 columns instead of 12)
    Line #257 (got 13 columns instead of 12)
    Line #258 (got 13 columns instead of 12)
    Line #259 (got 13 columns instead of 12)
    Line #260 (got 13 columns instead of 12)
    Line #261 (got 13 columns instead of 12)
    Line #262 (got 13 columns instead of 12)
    Line #263 (got 13 columns instead of 12)
    Line #264 (got 13 columns instead of 12)
    Line #265 (got 13 columns instead of 12)
    Line #266 (got 13 columns instead of 12)
    Line #267 (got 13 columns instead of 12)
    Line #268 (got 13 columns instead of 12)
    Line #269 (got 13 columns instead of 12)
    Line #270 (got 13 columns instead of 12)
    Line #271 (got 13 columns instead of 12)
    Line #272 (got 13 columns instead of 12)
    Line #273 (got 13 columns instead of 12)
    Line #274 (got 13 columns instead of 12)
    Line #275 (got 13 columns instead of 12)
    Line #276 (got 13 columns instead of 12)
    Line #277 (got 13 columns instead of 12)
    Line #278 (got 13 columns instead of 12)
    Line #279 (got 13 columns instead of 12)
    Line #280 (got 13 columns instead of 12)
    Line #281 (got 13 columns instead of 12)
    Line #282 (got 13 columns instead of 12)
    Line #283 (got 13 columns instead of 12)
    Line #284 (got 13 columns instead of 12)
    Line #285 (got 13 columns instead of 12)
    Line #286 (got 13 columns instead of 12)
    Line #287 (got 13 columns instead of 12)
    Line #288 (got 13 columns instead of 12)
    Line #289 (got 13 columns instead of 12)
    Line #290 (got 13 columns instead of 12)
    Line #291 (got 13 columns instead of 12)
    Line #292 (got 13 columns instead of 12)
    Line #293 (got 13 columns instead of 12)
    Line #294 (got 13 columns instead of 12)
    Line #295 (got 13 columns instead of 12)
    Line #296 (got 13 columns instead of 12)
    Line #297 (got 13 columns instead of 12)
    Line #298 (got 13 columns instead of 12)
    Line #299 (got 13 columns instead of 12)
    Line #300 (got 13 columns instead of 12)
    Line #301 (got 13 columns instead of 12)
    Line #302 (got 13 columns instead of 12)
    Line #303 (got 13 columns instead of 12)
    Line #304 (got 13 columns instead of 12)
    Line #305 (got 13 columns instead of 12)
    Line #306 (got 13 columns instead of 12)
    Line #307 (got 13 columns instead of 12)
    Line #308 (got 13 columns instead of 12)
    Line #309 (got 13 columns instead of 12)
    Line #310 (got 13 columns instead of 12)
    Line #311 (got 13 columns instead of 12)
    Line #312 (got 13 columns instead of 12)
    Line #313 (got 13 columns instead of 12)
    Line #314 (got 13 columns instead of 12)
    Line #315 (got 13 columns instead of 12)
    Line #316 (got 13 columns instead of 12)
    Line #317 (got 13 columns instead of 12)
    Line #318 (got 13 columns instead of 12)
    Line #319 (got 13 columns instead of 12)
    Line #320 (got 13 columns instead of 12)
    Line #321 (got 13 columns instead of 12)
    Line #322 (got 13 columns instead of 12)
    Line #323 (got 13 columns instead of 12)
    Line #324 (got 13 columns instead of 12)
    Line #325 (got 13 columns instead of 12)
    Line #326 (got 13 columns instead of 12)
    Line #327 (got 13 columns instead of 12)
    Line #328 (got 13 columns instead of 12)
    Line #329 (got 13 columns instead of 12)
    Line #330 (got 13 columns instead of 12)
    Line #331 (got 13 columns instead of 12)
    Line #332 (got 13 columns instead of 12)
    Line #333 (got 13 columns instead of 12)
    Line #334 (got 13 columns instead of 12)
    Line #335 (got 13 columns instead of 12)
    Line #336 (got 13 columns instead of 12)
    Line #337 (got 13 columns instead of 12)
    Line #338 (got 13 columns instead of 12)
    Line #339 (got 13 columns instead of 12)
    Line #340 (got 13 columns instead of 12)
    Line #341 (got 13 columns instead of 12)
    Line #342 (got 13 columns instead of 12)
    Line #343 (got 13 columns instead of 12)
    Line #344 (got 13 columns instead of 12)
    Line #345 (got 13 columns instead of 12)
    Line #346 (got 13 columns instead of 12)
    Line #347 (got 13 columns instead of 12)
    Line #348 (got 13 columns instead of 12)
    Line #349 (got 13 columns instead of 12)
    Line #350 (got 13 columns instead of 12)
    Line #351 (got 13 columns instead of 12)
    Line #352 (got 13 columns instead of 12)
    Line #353 (got 13 columns instead of 12)
    Line #354 (got 13 columns instead of 12)
    Line #355 (got 13 columns instead of 12)
    Line #356 (got 13 columns instead of 12)
    Line #357 (got 13 columns instead of 12)
    Line #358 (got 13 columns instead of 12)
    Line #359 (got 13 columns instead of 12)
    Line #360 (got 13 columns instead of 12)
    Line #361 (got 13 columns instead of 12)
    Line #362 (got 13 columns instead of 12)
    Line #363 (got 13 columns instead of 12)
    Line #364 (got 13 columns instead of 12)
    Line #365 (got 13 columns instead of 12)
    Line #366 (got 13 columns instead of 12)
    Line #367 (got 13 columns instead of 12)
    Line #368 (got 13 columns instead of 12)
    Line #369 (got 13 columns instead of 12)
    Line #370 (got 13 columns instead of 12)
    Line #371 (got 13 columns instead of 12)
    Line #372 (got 13 columns instead of 12)
    Line #373 (got 13 columns instead of 12)
    Line #374 (got 13 columns instead of 12)
    Line #375 (got 13 columns instead of 12)
    Line #376 (got 13 columns instead of 12)
    Line #377 (got 13 columns instead of 12)
    Line #378 (got 13 columns instead of 12)
    Line #379 (got 13 columns instead of 12)
    Line #380 (got 13 columns instead of 12)
    Line #381 (got 13 columns instead of 12)
    Line #382 (got 13 columns instead of 12)
    Line #383 (got 13 columns instead of 12)
    Line #384 (got 13 columns instead of 12)
    Line #385 (got 13 columns instead of 12)
    Line #386 (got 13 columns instead of 12)
    Line #387 (got 13 columns instead of 12)
    Line #388 (got 13 columns instead of 12)
    Line #389 (got 13 columns instead of 12)
    Line #390 (got 13 columns instead of 12)
    Line #391 (got 13 columns instead of 12)
    Line #392 (got 13 columns instead of 12)
    Line #393 (got 13 columns instead of 12)
    Line #394 (got 13 columns instead of 12)
    Line #395 (got 13 columns instead of 12)
    Line #396 (got 13 columns instead of 12)
    Line #397 (got 13 columns instead of 12)
    Line #398 (got 13 columns instead of 12)
    Line #399 (got 13 columns instead of 12)
    Line #400 (got 13 columns instead of 12)
    Line #401 (got 13 columns instead of 12)
    Line #402 (got 13 columns instead of 12)
    Line #403 (got 13 columns instead of 12)
    Line #404 (got 13 columns instead of 12)
    Line #405 (got 13 columns instead of 12)
    Line #406 (got 13 columns instead of 12)
    Line #407 (got 13 columns instead of 12)
    Line #408 (got 13 columns instead of 12)
    Line #409 (got 13 columns instead of 12)
    Line #410 (got 13 columns instead of 12)
    Line #411 (got 13 columns instead of 12)
    Line #412 (got 13 columns instead of 12)
    Line #413 (got 13 columns instead of 12)
    Line #414 (got 13 columns instead of 12)
    Line #415 (got 13 columns instead of 12)
    Line #416 (got 13 columns instead of 12)
    Line #417 (got 13 columns instead of 12)
    Line #418 (got 13 columns instead of 12)
    Line #419 (got 13 columns instead of 12)
    Line #420 (got 13 columns instead of 12)
    Line #421 (got 13 columns instead of 12)
    Line #422 (got 13 columns instead of 12)
    Line #423 (got 13 columns instead of 12)
    Line #424 (got 13 columns instead of 12)
    Line #425 (got 13 columns instead of 12)
    Line #426 (got 13 columns instead of 12)
    Line #427 (got 13 columns instead of 12)
    Line #428 (got 13 columns instead of 12)
    Line #429 (got 13 columns instead of 12)
    Line #430 (got 13 columns instead of 12)
    Line #431 (got 13 columns instead of 12)
    Line #432 (got 13 columns instead of 12)
    Line #433 (got 13 columns instead of 12)
    Line #434 (got 13 columns instead of 12)
    Line #435 (got 13 columns instead of 12)
    Line #436 (got 13 columns instead of 12)
    Line #437 (got 13 columns instead of 12)
    Line #438 (got 13 columns instead of 12)
    Line #439 (got 13 columns instead of 12)
    Line #440 (got 13 columns instead of 12)
    Line #441 (got 13 columns instead of 12)
    Line #442 (got 13 columns instead of 12)
    Line #443 (got 13 columns instead of 12)
    Line #444 (got 13 columns instead of 12)
    Line #445 (got 13 columns instead of 12)
    Line #446 (got 13 columns instead of 12)
    Line #447 (got 13 columns instead of 12)
    Line #448 (got 13 columns instead of 12)
    Line #449 (got 13 columns instead of 12)
    Line #450 (got 13 columns instead of 12)
    Line #451 (got 13 columns instead of 12)
    Line #452 (got 13 columns instead of 12)
    Line #453 (got 13 columns instead of 12)
    Line #454 (got 13 columns instead of 12)
    Line #455 (got 13 columns instead of 12)
    Line #456 (got 13 columns instead of 12)
    Line #457 (got 13 columns instead of 12)
    Line #458 (got 13 columns instead of 12)
    Line #459 (got 13 columns instead of 12)
    Line #460 (got 13 columns instead of 12)
    Line #461 (got 13 columns instead of 12)
    Line #462 (got 13 columns instead of 12)
    Line #463 (got 13 columns instead of 12)
    Line #464 (got 13 columns instead of 12)
    Line #465 (got 13 columns instead of 12)
    Line #466 (got 13 columns instead of 12)
    Line #467 (got 13 columns instead of 12)
    Line #468 (got 13 columns instead of 12)
    Line #469 (got 13 columns instead of 12)
    Line #470 (got 13 columns instead of 12)
    Line #471 (got 13 columns instead of 12)
    Line #472 (got 13 columns instead of 12)
    Line #473 (got 13 columns instead of 12)
    Line #474 (got 13 columns instead of 12)
    Line #475 (got 13 columns instead of 12)
    Line #476 (got 13 columns instead of 12)
    Line #477 (got 13 columns instead of 12)
    Line #478 (got 13 columns instead of 12)
    Line #479 (got 13 columns instead of 12)
    Line #480 (got 13 columns instead of 12)
    Line #481 (got 13 columns instead of 12)
    Line #482 (got 13 columns instead of 12)
    Line #483 (got 13 columns instead of 12)
    Line #484 (got 13 columns instead of 12)
    Line #485 (got 13 columns instead of 12)
    Line #486 (got 13 columns instead of 12)
    Line #487 (got 13 columns instead of 12)
    Line #488 (got 13 columns instead of 12)
    Line #489 (got 13 columns instead of 12)
    Line #490 (got 13 columns instead of 12)
    Line #491 (got 13 columns instead of 12)
    Line #492 (got 13 columns instead of 12)
    Line #493 (got 13 columns instead of 12)
    Line #494 (got 13 columns instead of 12)
    Line #495 (got 13 columns instead of 12)
    Line #496 (got 13 columns instead of 12)
    Line #497 (got 13 columns instead of 12)
    Line #498 (got 13 columns instead of 12)
    Line #499 (got 13 columns instead of 12)
    Line #500 (got 13 columns instead of 12)
    Line #501 (got 13 columns instead of 12)
    Line #502 (got 13 columns instead of 12)
    Line #503 (got 13 columns instead of 12)
    Line #504 (got 13 columns instead of 12)
    Line #505 (got 13 columns instead of 12)
    Line #506 (got 13 columns instead of 12)
    Line #507 (got 13 columns instead of 12)
    Line #508 (got 13 columns instead of 12)
    Line #509 (got 13 columns instead of 12)
    Line #510 (got 13 columns instead of 12)
    Line #511 (got 13 columns instead of 12)
    Line #512 (got 13 columns instead of 12)
    Line #513 (got 13 columns instead of 12)
    Line #514 (got 13 columns instead of 12)
    Line #515 (got 13 columns instead of 12)
    Line #516 (got 13 columns instead of 12)
    Line #517 (got 13 columns instead of 12)
    Line #518 (got 13 columns instead of 12)
    Line #519 (got 13 columns instead of 12)
    Line #520 (got 13 columns instead of 12)
    Line #521 (got 13 columns instead of 12)
    Line #522 (got 13 columns instead of 12)
    Line #523 (got 13 columns instead of 12)
    Line #524 (got 13 columns instead of 12)
    Line #525 (got 13 columns instead of 12)
    Line #526 (got 13 columns instead of 12)
    Line #527 (got 13 columns instead of 12)
    Line #528 (got 13 columns instead of 12)
    Line #529 (got 13 columns instead of 12)
    Line #530 (got 13 columns instead of 12)
    Line #531 (got 13 columns instead of 12)
    Line #532 (got 13 columns instead of 12)
    Line #533 (got 13 columns instead of 12)
    Line #534 (got 13 columns instead of 12)
    Line #535 (got 13 columns instead of 12)
    Line #536 (got 13 columns instead of 12)
    Line #537 (got 13 columns instead of 12)
    Line #538 (got 13 columns instead of 12)
    Line #539 (got 13 columns instead of 12)
    Line #540 (got 13 columns instead of 12)
    Line #541 (got 13 columns instead of 12)
    Line #542 (got 13 columns instead of 12)
    Line #543 (got 13 columns instead of 12)
    Line #544 (got 13 columns instead of 12)
    Line #545 (got 13 columns instead of 12)
    Line #546 (got 13 columns instead of 12)
    Line #547 (got 13 columns instead of 12)
    Line #548 (got 13 columns instead of 12)
    Line #549 (got 13 columns instead of 12)
    Line #550 (got 13 columns instead of 12)
    Line #551 (got 13 columns instead of 12)
    Line #552 (got 13 columns instead of 12)
    Line #553 (got 13 columns instead of 12)
    Line #554 (got 13 columns instead of 12)
    Line #555 (got 13 columns instead of 12)
    Line #556 (got 13 columns instead of 12)
    Line #557 (got 13 columns instead of 12)
    Line #558 (got 13 columns instead of 12)
    Line #559 (got 13 columns instead of 12)
    Line #560 (got 13 columns instead of 12)
    Line #561 (got 13 columns instead of 12)
    Line #562 (got 13 columns instead of 12)
    Line #563 (got 13 columns instead of 12)
    Line #564 (got 13 columns instead of 12)
    Line #565 (got 13 columns instead of 12)
    Line #566 (got 13 columns instead of 12)
    Line #567 (got 13 columns instead of 12)
    Line #568 (got 13 columns instead of 12)
    Line #569 (got 13 columns instead of 12)
    Line #570 (got 13 columns instead of 12)
    Line #571 (got 13 columns instead of 12)
    Line #572 (got 13 columns instead of 12)
    Line #573 (got 13 columns instead of 12)
    Line #574 (got 13 columns instead of 12)
    Line #575 (got 13 columns instead of 12)
    Line #576 (got 13 columns instead of 12)
    Line #577 (got 13 columns instead of 12)
    Line #578 (got 13 columns instead of 12)
    Line #579 (got 13 columns instead of 12)
    Line #580 (got 13 columns instead of 12)
    Line #581 (got 13 columns instead of 12)
    Line #582 (got 13 columns instead of 12)
    Line #583 (got 13 columns instead of 12)
    Line #584 (got 13 columns instead of 12)
    Line #585 (got 13 columns instead of 12)
    Line #586 (got 13 columns instead of 12)
    Line #587 (got 13 columns instead of 12)
    Line #588 (got 13 columns instead of 12)
    Line #589 (got 13 columns instead of 12)
    Line #590 (got 13 columns instead of 12)
    Line #591 (got 13 columns instead of 12)
    Line #592 (got 13 columns instead of 12)
    Line #593 (got 13 columns instead of 12)
    Line #594 (got 13 columns instead of 12)
    Line #595 (got 13 columns instead of 12)
    Line #596 (got 13 columns instead of 12)
    Line #597 (got 13 columns instead of 12)
    Line #598 (got 13 columns instead of 12)
    Line #599 (got 13 columns instead of 12)
    Line #600 (got 13 columns instead of 12)
    Line #601 (got 13 columns instead of 12)
    Line #602 (got 13 columns instead of 12)
    Line #603 (got 13 columns instead of 12)
    Line #604 (got 13 columns instead of 12)
    Line #605 (got 13 columns instead of 12)
    Line #606 (got 13 columns instead of 12)
    Line #607 (got 13 columns instead of 12)
    Line #608 (got 13 columns instead of 12)
    Line #609 (got 13 columns instead of 12)
    Line #610 (got 13 columns instead of 12)
    Line #611 (got 13 columns instead of 12)
    Line #612 (got 13 columns instead of 12)
    Line #613 (got 13 columns instead of 12)
    Line #614 (got 13 columns instead of 12)
    Line #615 (got 13 columns instead of 12)
    Line #616 (got 13 columns instead of 12)
    Line #617 (got 13 columns instead of 12)
    Line #618 (got 13 columns instead of 12)
    Line #619 (got 13 columns instead of 12)
    Line #620 (got 13 columns instead of 12)
    Line #621 (got 13 columns instead of 12)
    Line #622 (got 13 columns instead of 12)
    Line #623 (got 13 columns instead of 12)
    Line #624 (got 13 columns instead of 12)
    Line #625 (got 13 columns instead of 12)
    Line #626 (got 13 columns instead of 12)
    Line #627 (got 13 columns instead of 12)
    Line #628 (got 13 columns instead of 12)
    Line #629 (got 13 columns instead of 12)
    Line #630 (got 13 columns instead of 12)
    Line #631 (got 13 columns instead of 12)
    Line #632 (got 13 columns instead of 12)
    Line #633 (got 13 columns instead of 12)
    Line #634 (got 13 columns instead of 12)
    Line #635 (got 13 columns instead of 12)
    Line #636 (got 13 columns instead of 12)
    Line #637 (got 13 columns instead of 12)
    Line #638 (got 13 columns instead of 12)
    Line #639 (got 13 columns instead of 12)
    Line #640 (got 13 columns instead of 12)
    Line #641 (got 13 columns instead of 12)
    Line #642 (got 13 columns instead of 12)
    Line #643 (got 13 columns instead of 12)
    Line #644 (got 13 columns instead of 12)
    Line #645 (got 13 columns instead of 12)
    Line #646 (got 13 columns instead of 12)
    Line #647 (got 13 columns instead of 12)
    Line #648 (got 13 columns instead of 12)
    Line #649 (got 13 columns instead of 12)
    Line #650 (got 13 columns instead of 12)
    Line #651 (got 13 columns instead of 12)
    Line #652 (got 13 columns instead of 12)
    Line #653 (got 13 columns instead of 12)
    Line #654 (got 13 columns instead of 12)
    Line #655 (got 13 columns instead of 12)
    Line #656 (got 13 columns instead of 12)
    Line #657 (got 13 columns instead of 12)
    Line #658 (got 13 columns instead of 12)
    Line #659 (got 13 columns instead of 12)
    Line #660 (got 13 columns instead of 12)
    Line #661 (got 13 columns instead of 12)
    Line #662 (got 13 columns instead of 12)
    Line #663 (got 13 columns instead of 12)
    Line #664 (got 13 columns instead of 12)
    Line #665 (got 13 columns instead of 12)
    Line #666 (got 13 columns instead of 12)
    Line #667 (got 13 columns instead of 12)
    Line #668 (got 13 columns instead of 12)
    Line #669 (got 13 columns instead of 12)
    Line #670 (got 13 columns instead of 12)
    Line #671 (got 13 columns instead of 12)
    Line #672 (got 13 columns instead of 12)
    Line #673 (got 13 columns instead of 12)
    Line #674 (got 13 columns instead of 12)
    Line #675 (got 13 columns instead of 12)
    Line #676 (got 13 columns instead of 12)
    Line #677 (got 13 columns instead of 12)
    Line #678 (got 13 columns instead of 12)
    Line #679 (got 13 columns instead of 12)
    Line #680 (got 13 columns instead of 12)
    Line #681 (got 13 columns instead of 12)
    Line #682 (got 13 columns instead of 12)
    Line #683 (got 13 columns instead of 12)
    Line #684 (got 13 columns instead of 12)
    Line #685 (got 13 columns instead of 12)
    Line #686 (got 13 columns instead of 12)
    Line #687 (got 13 columns instead of 12)
    Line #688 (got 13 columns instead of 12)
    Line #689 (got 13 columns instead of 12)
    Line #690 (got 13 columns instead of 12)
    Line #691 (got 13 columns instead of 12)
    Line #692 (got 13 columns instead of 12)
    Line #693 (got 13 columns instead of 12)
    Line #694 (got 13 columns instead of 12)
    Line #695 (got 13 columns instead of 12)
    Line #696 (got 13 columns instead of 12)
    Line #697 (got 13 columns instead of 12)
    Line #698 (got 13 columns instead of 12)
    Line #699 (got 13 columns instead of 12)
    Line #700 (got 13 columns instead of 12)
    Line #701 (got 13 columns instead of 12)
    Line #702 (got 13 columns instead of 12)
    Line #703 (got 13 columns instead of 12)
    Line #704 (got 13 columns instead of 12)
    Line #705 (got 13 columns instead of 12)
    Line #706 (got 13 columns instead of 12)
    Line #707 (got 13 columns instead of 12)
    Line #708 (got 13 columns instead of 12)
    Line #709 (got 13 columns instead of 12)
    Line #710 (got 13 columns instead of 12)
    Line #711 (got 13 columns instead of 12)
    Line #712 (got 13 columns instead of 12)
    Line #713 (got 13 columns instead of 12)
    Line #714 (got 13 columns instead of 12)
    Line #715 (got 13 columns instead of 12)
    Line #716 (got 13 columns instead of 12)
    Line #717 (got 13 columns instead of 12)
    Line #718 (got 13 columns instead of 12)
    Line #719 (got 13 columns instead of 12)
    Line #720 (got 13 columns instead of 12)
    Line #721 (got 13 columns instead of 12)
    Line #722 (got 13 columns instead of 12)
    Line #723 (got 13 columns instead of 12)
    Line #724 (got 13 columns instead of 12)
    Line #725 (got 13 columns instead of 12)
    Line #726 (got 13 columns instead of 12)
    Line #727 (got 13 columns instead of 12)
    Line #728 (got 13 columns instead of 12)
    Line #729 (got 13 columns instead of 12)
    Line #730 (got 13 columns instead of 12)
    Line #731 (got 13 columns instead of 12)
    Line #732 (got 13 columns instead of 12)
    Line #733 (got 13 columns instead of 12)
    Line #734 (got 13 columns instead of 12)
    Line #735 (got 13 columns instead of 12)
    Line #736 (got 13 columns instead of 12)
    Line #737 (got 13 columns instead of 12)
    Line #738 (got 13 columns instead of 12)
    Line #739 (got 13 columns instead of 12)
    Line #740 (got 13 columns instead of 12)
    Line #741 (got 13 columns instead of 12)
    Line #742 (got 13 columns instead of 12)
    Line #743 (got 13 columns instead of 12)
    Line #744 (got 13 columns instead of 12)
    Line #745 (got 13 columns instead of 12)
    Line #746 (got 13 columns instead of 12)
    Line #747 (got 13 columns instead of 12)
    Line #748 (got 13 columns instead of 12)
    Line #749 (got 13 columns instead of 12)
    Line #750 (got 13 columns instead of 12)
    Line #751 (got 13 columns instead of 12)
    Line #752 (got 13 columns instead of 12)
    Line #753 (got 13 columns instead of 12)
    Line #754 (got 13 columns instead of 12)
    Line #755 (got 13 columns instead of 12)
    Line #756 (got 13 columns instead of 12)
    Line #757 (got 13 columns instead of 12)
    Line #758 (got 13 columns instead of 12)
    Line #759 (got 13 columns instead of 12)
    Line #760 (got 13 columns instead of 12)
    Line #761 (got 13 columns instead of 12)
    Line #762 (got 13 columns instead of 12)
    Line #763 (got 13 columns instead of 12)
    Line #764 (got 13 columns instead of 12)
    Line #765 (got 13 columns instead of 12)
    Line #766 (got 13 columns instead of 12)
    Line #767 (got 13 columns instead of 12)
    Line #768 (got 13 columns instead of 12)
    Line #769 (got 13 columns instead of 12)
    Line #770 (got 13 columns instead of 12)
    Line #771 (got 13 columns instead of 12)
    Line #772 (got 13 columns instead of 12)
    Line #773 (got 13 columns instead of 12)
    Line #774 (got 13 columns instead of 12)
    Line #775 (got 13 columns instead of 12)
    Line #776 (got 13 columns instead of 12)
    Line #777 (got 13 columns instead of 12)
    Line #778 (got 13 columns instead of 12)
    Line #779 (got 13 columns instead of 12)
    Line #780 (got 13 columns instead of 12)
    Line #781 (got 13 columns instead of 12)
    Line #782 (got 13 columns instead of 12)
    Line #783 (got 13 columns instead of 12)
    Line #784 (got 13 columns instead of 12)
    Line #785 (got 13 columns instead of 12)
    Line #786 (got 13 columns instead of 12)
    Line #787 (got 13 columns instead of 12)
    Line #788 (got 13 columns instead of 12)
    Line #789 (got 13 columns instead of 12)
    Line #790 (got 13 columns instead of 12)
    Line #791 (got 13 columns instead of 12)
    Line #792 (got 13 columns instead of 12)
    Line #793 (got 13 columns instead of 12)
    Line #794 (got 13 columns instead of 12)
    Line #795 (got 13 columns instead of 12)
    Line #796 (got 13 columns instead of 12)
    Line #797 (got 13 columns instead of 12)
    Line #798 (got 13 columns instead of 12)
    Line #799 (got 13 columns instead of 12)
    Line #800 (got 13 columns instead of 12)
    Line #801 (got 13 columns instead of 12)
    Line #802 (got 13 columns instead of 12)
    Line #803 (got 13 columns instead of 12)
    Line #804 (got 13 columns instead of 12)
    Line #805 (got 13 columns instead of 12)
    Line #806 (got 13 columns instead of 12)
    Line #807 (got 13 columns instead of 12)
    Line #808 (got 13 columns instead of 12)
    Line #809 (got 13 columns instead of 12)
    Line #810 (got 13 columns instead of 12)
    Line #811 (got 13 columns instead of 12)
    Line #812 (got 13 columns instead of 12)
    Line #813 (got 13 columns instead of 12)
    Line #814 (got 13 columns instead of 12)
    Line #815 (got 13 columns instead of 12)
    Line #816 (got 13 columns instead of 12)
    Line #817 (got 13 columns instead of 12)
    Line #818 (got 13 columns instead of 12)
    Line #819 (got 13 columns instead of 12)
    Line #820 (got 13 columns instead of 12)
    Line #821 (got 13 columns instead of 12)
    Line #822 (got 13 columns instead of 12)
    Line #823 (got 13 columns instead of 12)
    Line #824 (got 13 columns instead of 12)
    Line #825 (got 13 columns instead of 12)
    Line #826 (got 13 columns instead of 12)
    Line #827 (got 13 columns instead of 12)
    Line #828 (got 13 columns instead of 12)
    Line #829 (got 13 columns instead of 12)
    Line #830 (got 13 columns instead of 12)
    Line #831 (got 13 columns instead of 12)
    Line #832 (got 13 columns instead of 12)
    Line #833 (got 13 columns instead of 12)
    Line #834 (got 13 columns instead of 12)
    Line #835 (got 13 columns instead of 12)
    Line #836 (got 13 columns instead of 12)
    Line #837 (got 13 columns instead of 12)
    Line #838 (got 13 columns instead of 12)
    Line #839 (got 13 columns instead of 12)
    Line #840 (got 13 columns instead of 12)
    Line #841 (got 13 columns instead of 12)
    Line #842 (got 13 columns instead of 12)
    Line #843 (got 13 columns instead of 12)
    Line #844 (got 13 columns instead of 12)
    Line #845 (got 13 columns instead of 12)
    Line #846 (got 13 columns instead of 12)
    Line #847 (got 13 columns instead of 12)
    Line #848 (got 13 columns instead of 12)
    Line #849 (got 13 columns instead of 12)
    Line #850 (got 13 columns instead of 12)
    Line #851 (got 13 columns instead of 12)
    Line #852 (got 13 columns instead of 12)
    Line #853 (got 13 columns instead of 12)
    Line #854 (got 13 columns instead of 12)
    Line #855 (got 13 columns instead of 12)
    Line #856 (got 13 columns instead of 12)
    Line #857 (got 13 columns instead of 12)
    Line #858 (got 13 columns instead of 12)
    Line #859 (got 13 columns instead of 12)
    Line #860 (got 13 columns instead of 12)
    Line #861 (got 13 columns instead of 12)
    Line #862 (got 13 columns instead of 12)
    Line #863 (got 13 columns instead of 12)
    Line #864 (got 13 columns instead of 12)
    Line #865 (got 13 columns instead of 12)
    Line #866 (got 13 columns instead of 12)
    Line #867 (got 13 columns instead of 12)
    Line #868 (got 13 columns instead of 12)
    Line #869 (got 13 columns instead of 12)
    Line #870 (got 13 columns instead of 12)
    Line #871 (got 13 columns instead of 12)
    Line #872 (got 13 columns instead of 12)
    Line #873 (got 13 columns instead of 12)
    Line #874 (got 13 columns instead of 12)
    Line #875 (got 13 columns instead of 12)
    Line #876 (got 13 columns instead of 12)
    Line #877 (got 13 columns instead of 12)
    Line #878 (got 13 columns instead of 12)
    Line #879 (got 13 columns instead of 12)
    Line #880 (got 13 columns instead of 12)
    Line #881 (got 13 columns instead of 12)
    Line #882 (got 13 columns instead of 12)
    Line #883 (got 13 columns instead of 12)
    Line #884 (got 13 columns instead of 12)
    Line #885 (got 13 columns instead of 12)
    Line #886 (got 13 columns instead of 12)
    Line #887 (got 13 columns instead of 12)
    Line #888 (got 13 columns instead of 12)
    Line #889 (got 13 columns instead of 12)
    Line #890 (got 13 columns instead of 12)
    Line #891 (got 13 columns instead of 12)
    Line #892 (got 13 columns instead of 12)

In [28]:
import pandas as pd

In [29]:
data=pd.read_csv("C:/Users/Harisinghbisht/Desktop/SkillSanta/01_data.csv")

In [30]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [31]:
new_data=data[['PassengerId','Survived','Pclass']]

In [32]:
new_data

PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
5              6         0       3
6              7         0       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
11            12         1       1
12            13         0       3
13            14         0       3
14            15         0       3
15            16         1       2
16            17         0       3
17            18         1       2
18            19         0       3
19            20         1       3
20            21         0       2
21            22         1       2
22            23         1       3
23            24         1       1
24            25         0       3
25            26         1       3
26            27         0       3
27            28         0       1
28            29         1       3
29            30         0       3
..           ...       ...     ...
861          862         0       2
862          863         1       1
863          864         0       3
864          865         0       2
865          866         1       2
866          867         1       2
867          868         0       1
868          869         0       3
869          870         1       3
870          871         0       3
871          872         1       1
872          873         0       1
873          874         0       3
874          875         1       2
875          876         1       3
876          877         0       3
877          878         0       3
878          879         0       3
879          880         1       1
880          881         1       2
881          882         0       3
882          883         0       3
883          884         0       2
884          885         0       3
885          886         0       3
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]